"""subclass EmailMessage to simplify file attachments and building/sending an email"""
import os
from typing import Union, List
from email.message import EmailMessage
import mimetypes
import requests
import smtplib
from dotenv import load_dotenv

import application.auth.auth_confidential_client_secret as azure_auth

load_dotenv()

LOGIN_EMAIL_ADDRESS = os.environ.get("LOGIN_EMAIL_ADDRESS")
LOGIN_EMAIL_PASSWORD = os.environ.get("LOGIN_EMAIL_PASSWORD")
SENDER_EMAIL_ADDRESS = os.environ.get("SENDER_EMAIL_ADDRESS")
SENDER_USER_ID = os.environ.get("SENDER_USER_ID")

class CustomEmailMessage(EmailMessage):
    """
    adding a method that simplifies adding file attachments
    """
    def new_file_attachment(self, _file:str):
        """Takes a filepath and attaches the file to an email"""
        ctype, _ = mimetypes.guess_type(_file)
        maintype, subtype = ctype.split('/', 1)
        with open(_file,'rb') as handler:
            self.add_attachment(
                handler.read(),
                maintype=maintype,
                subtype=subtype,
                filename=os.path.basename(_file)
            )
    def new_attachment_bytestream(self, buffer: bytes, filename: str):
        """Takes an BytesIO-generated bytes and desired filename and attaches it as a file"""
        maintype, _, subtype = (
            mimetypes.guess_type(filename)[0] or 'application/octet-stream'
            ).partition("/")
        self.add_attachment(
            buffer,
            maintype=maintype,
            subtype=subtype,
            filename=filename
        )


def send_email_old(recipients, subject, template_msg, msg_list, 
        msg_signature, attachments: Union[str,list,tuple]=None):
    """
    conveinece function for building and sending an email
        using the function variables
    """
    email = CustomEmailMessage()
    email['Subject'] = subject
    email['To'] = recipients
    email['From'] = SENDER_EMAIL_ADDRESS
    email.set_content("")
    email.add_alternative(f"""
        <font face="Roboto, sans-serif">
        <p>{template_msg}</p>
        <p>{msg_list}</p>
        <p>{msg_signature}</p>
        </font>
        """, subtype='html')

    if attachments:
        # does not account for a list of tuples!
        if isinstance(attachments,list):
            for attachment in attachments:
                email.new_file_attachment(attachment)
        elif isinstance(attachments,tuple):
            file_data, file_name = attachments
            email.new_attachment_bytestream(buffer=file_data,filename=file_name)
        else:
            email.new_file_attachment(attachments)

    # send Email
    mailserver = smtplib.SMTP('smtp.office365.com',587)
    mailserver.starttls()
    mailserver.login(LOGIN_EMAIL_ADDRESS, LOGIN_EMAIL_PASSWORD)
    mailserver.send_message(email)
    mailserver.quit()

def send_email(recipients: list, subject: str, message: str=None, attachments: List[tuple]=None):
    """ Send email as a different user using Microsoft Graph API"""

    recipients_formatted = [{"emailAddress": {"address": recipient}} for recipient in recipients]
    sendmail_request_body = {
        "subject": f"{subject}",
        "toRecipients": recipients_formatted,
        "from": {
                "emailAddress": {
                    "address": f"{SENDER_EMAIL_ADDRESS}"
                }
        },
        "body": {
            "contentType": "Text",
            "content": f"{message}"
        }
    }
    if attachments:
        attachments_formatted = [
            {                
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": f"{name}",
                "contentType": "application/vnd.ms-excel",
                "contentBytes": f"{content}"
            } for name, content in attachments
        ]
        sendmail_request_body.update({"attachments": attachments_formatted})

    api_url = f"https://graph.microsoft.com/v1.0/users/{SENDER_USER_ID}/sendMail"
    headers = {
        "Content-type": "application/json",
        "Authorization": 'Bearer ' + azure_auth.get_auth_token_for_ms_graph()}
    r = requests.post(api_url, headers=headers, json={"message": sendmail_request_body})
    print(r.content)

    return r.status_code